Revert "Staging: android: binder: Add binder buffers to kmemleak"
This reverts commit 0ba16099e475d16a940221a0a37835cd9d29b656.

Fixes this error:

android/binder.c: In function 'binder_alloc_buf':
android/binder.c:833:2: error: implicit declaration of function 'kmemleak_alloc' [-Werror=implicit-function-declaration]
android/binder.c: In function 'binder_free_buf':
android/binder.c:899:2: error: implicit declaration of function 'kmemleak_free' [-Werror=implicit-function-declaration]